conky.config = {
    alignment = 'top_right',
    background = true,
    double_buffer = true,
    no_buffers = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'normal',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    use_xft = true,
    font = 'monospace:size=11',
    xftalpha = 1,
    update_interval = 1.0,
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,
    show_graph_scale = false,
    show_graph_range = false,
    lua_load = 'svg_test.lua',
    lua_draw_hook_pre = 'conky_svg_test_draw',
    minimum_width = 600,
    minimum_height = 400,
    maximum_width = 600,
    gap_x = 800,
    gap_y = 400,
}

conky.text = [[

]]
