conky.config = {
  background = true,
  out_to_x = true,
  double_buffer = true,
  use_xft = true,
  x = 0,
  y = 30,
  -- xftfont deprecated in newer conky; use 'font' instead if needed
  font = 'Sans:size=10',
  own_window = true,
  own_window_transparent = false,
  own_window_type = 'desktop',
  update_interval = 1,
  total_run_times = 0,
  minimum_width = 1920,
  minimum_height = 1020,
  lua_load = 'main.lua',
  lua_draw_hook_pre = 'conky_core_main',
  lua_shutdown_hook = 'conky_cleanup',
}

conky.text = [[
${voffset 10}${goto 0}Conky NextGen draw.lua widget test
]]
