conky.config = {
    lua_load = 'main.lua',
    minimum_width = 360,
    minimum_height = 220,
    alignment = 'top_left',
    gap_x = 0, gap_y = 0,
    own_window = true,
    own_window_type = 'normal',
    own_window_argb_visual = true,
    own_window_argb_value = 180,
    own_window_colour = '#141618',
    own_window_transparent = false,
    double_buffer = true,
    update_interval = 0.5,
    use_xft = true,
    font = 'Sans:size=10',
    default_color = '#ffffff',
    override_utf8_locale = true,
    lua_draw_hook_pre = 'conky_core_main',
}

conky.text = [[]]
